name: Events Demo 1
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
      - develop
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "CHANGELOG.md"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: |
            dist
            package.json
