name: Using resuseable workflows
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
      - develop
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "CHANGELOG.md"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          caching: "true"
      - name: Run ESLint
        run: |
          npm run lint
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v4
  #     - name: Load & cache dependencies
  #       id: cached-deps
  #       uses: ./.github/actions/cached-deps
  #       with:
  #         caching: "true"
  #     - name: Output information
  #       run: echo "${{ steps.cached-deps.outputs.used-cache }}"
  #     - name: Run tests
  #       # continue-on-error: true
  #       id: run-tests
  #       run: npm test
  #     - name: Upload test results
  #       if: failure() && steps.run-tests.outcome == 'failure'
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: test-report
  #         path: test.json
  build:
    #needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
        with:
          caching: "true"
      - name: Build project
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: |
            dist
  output-env:
    environment: Dev
    runs-on: ubuntu-latest
    needs: build
    outputs:
      AWS_ACCESS_KEY_ID: ${{ steps.output-env.outputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ steps.output-env.outputs.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: output-env
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_OUTPUT
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_OUTPUT
  deploy-dev:
    needs: output-env
    uses: ./.github/workflows/reuseable.yml
    with:
      artifact-name: dist-artifacts
    secrets:
      AWS_ACCESS_KEY_ID: ${{ needs.output-env.outputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ needs.output-env.outputs.AWS_SECRET_ACCESS_KEY }}
  print-deploy-result:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Output deployment result
        run: echo "${{ needs.deploy-dev.outputs.result }}"
  report:
    needs: [lint, deploy-dev]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ github }}"
