name: Deploy Project
on: [push]
# This workflow deploys the project when code is pushed or manually triggered.
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run tests
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build project
        run: npm run build
