name: Output information
on:
  issues:
    types: [opened, edited, closed]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Details
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Action: ${{ github.event.action }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
