name: Reuseable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the artifact to download"
        required: true
        default: dist
        type: string
    outputs:
      result:
        description: "Result of the deployment"
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    environment: Dev
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./dist
      - name: Output contents
        run: |
          echo "Contents of dist:"
          ls
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Deploy site
        uses: ./.github/actions/deploy-s3-javascript
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: gyi-custom-action-hosting
          dist-folder: ./dist
      - name: Set result ouput
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
